{"name": "test_add_fail[数字+列表错误]", "status": "passed", "parameters": [{"name": "a", "value": "1"}, {"name": "b", "value": "[1, 2]"}, {"name": "error_type", "value": "'TypeError'"}], "start": 1623945377539, "stop": 1623945377539, "uuid": "1235ac8e-bb06-410b-b52e-df0d2787494c", "historyId": "15db6cdeff522c9029531ceea01c555d", "testCaseId": "1b5aab2181c21923f6bd8223ee598e23", "fullName": "Test_2021_06_17.test_cal.test_cal.TestAddDivision#test_add_fail", "labels": [{"name": "parentSuite", "value": "Test_2021_06_17.test_cal"}, {"name": "suite", "value": "test_cal"}, {"name": "subSuite", "value": "TestAddDivision"}, {"name": "host", "value": "192.168.8.102"}, {"name": "thread", "value": "27956-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_2021_06_17.test_cal.test_cal"}]}