{"name": "test_add_fail[数字+字符串错误]", "status": "passed", "parameters": [{"name": "a", "value": "1"}, {"name": "b", "value": "'2'"}, {"name": "error_type", "value": "'TypeError'"}], "start": 1623945377533, "stop": 1623945377533, "uuid": "9bcc3afc-39dd-4ee1-9fcc-0b767f8d1567", "historyId": "4057b389ada215182f9cc8de0d07e30b", "testCaseId": "1b5aab2181c21923f6bd8223ee598e23", "fullName": "Test_2021_06_17.test_cal.test_cal.TestAddDivision#test_add_fail", "labels": [{"name": "parentSuite", "value": "Test_2021_06_17.test_cal"}, {"name": "suite", "value": "test_cal"}, {"name": "subSuite", "value": "TestAddDivision"}, {"name": "host", "value": "192.168.8.102"}, {"name": "thread", "value": "27956-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_2021_06_17.test_cal.test_cal"}]}